add junit report action to workflows

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -28,4 +28,13 @@ jobs:
         run: cd ruby && bundle install
       - name: Run tests
         run: cd ruby && bundle exec rake
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'ruby/junit-report.xml'
+          test_files_prefix: 'ruby/'
+          fail_on_failure: true
+          detailed_summary: true
+
 
